### ISSUE TITLE
Missing "hacktoberfest" topic

### ISSUE THREAD

**Issue by zoffixznet** [Raku/modules.raku.org#133]
Hacktoberfest has just changed rules that only repos with "hacktoberfest" topic will be counted towards the prize: https://github.com/digitalocean/hacktoberfest/pull/596

So lacking that [topic in the "About" box](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/classifying-your-repository-with-topics) ensures no hacktoberesters will be interested in contributing

**Comment by JJ** [comment]
Added. We're doing it one by one, you know. We just knew about this yesterday.
